### ISSUE TITLE
VCL rules Question

### ISSUE THREAD

**Issue by blindpet** [varnish/libvmod-shield#5]
I have this working, for sub vcl_receive, do I need equivalents in vcl miss or anywhere else to be effective against DDoS?

    sub vcl_recv {
	# Check requests per second using vsthrottle
	if (vsthrottle.is_denied(client.identity, 15, 10s)) {
        # Client has exceeded 15 reqs per 10s, reset connection using shield
		shield.conn_reset();
		return (synth(429, "Too Many Requests"));
		}
    }

**Comment by lkarsten** [comment]
This is an issue tracker, not a help forum. Please come by on IRC (irc.linpro.no / #varnish ) if you need help.
